export const USERCENTRICS_SETTINGS_ID = process.env.NEXT_PUBLIC_USERCENTRICS_SETTINGS_ID || '9suQr3rGddL3Tb'

/** Usercentrics Admin → Appearance → Styling → Custom CSS (V3 Shadow DOM selectors). */
export const USERCENTRICS_CUSTOM_CSS_RELATIVE_PATH = 'src/components/cookie-consent/usercentrics.custom.css'

export const USERCENTRICS_SGTM_ORIGIN = (
  process.env.NEXT_PUBLIC_USERCENTRICS_SGTM_ORIGIN || 'https://cloud.server.utekos.no'
).replace(/\/$/, '')

export const USERCENTRICS_CONSENT_EVENT_NAME =
  process.env.NEXT_PUBLIC_USERCENTRICS_CONSENT_EVENT_NAME || 'ucEvent'

export const USERCENTRICS_CONSENT_COOKIE_NAME = 'ucConsentAllowedDps'

export const USERCENTRICS_GOOGLE_ANALYTICS_SERVICE_NAME =
  process.env.NEXT_PUBLIC_USERCENTRICS_GOOGLE_ANALYTICS_SERVICE_NAME || 'Google Analytics'

/** Must match the exact DPS label in Usercentrics Admin and GTM Data Layer Variable names. */

export const USERCENTRICS_GOOGLE_ADS_SERVICE_NAME =
  process.env.NEXT_PUBLIC_USERCENTRICS_GOOGLE_ADS_SERVICE_NAME || 'Google Ads'

export const USERCENTRICS_META_SERVICE_NAME =
  process.env.NEXT_PUBLIC_USERCENTRICS_META_SERVICE_NAME || 'Facebook Pixel'

export const USERCENTRICS_MICROSOFT_SERVICE_NAME =
  process.env.NEXT_PUBLIC_USERCENTRICS_MICROSOFT_SERVICE_NAME || 'Microsoft Advertising Remarketing'

export const USERCENTRICS_CLARITY_SERVICE_NAME =
  process.env.NEXT_PUBLIC_USERCENTRICS_CLARITY_SERVICE_NAME || 'Microsoft Clarity'

export const USERCENTRICS_POSTHOG_SERVICE_NAME =
  process.env.NEXT_PUBLIC_USERCENTRICS_POSTHOG_SERVICE_NAME || 'PostHog'

export const USERCENTRICS_VERCEL_ANALYTICS_SERVICE_NAME =
  process.env.NEXT_PUBLIC_USERCENTRICS_VERCEL_ANALYTICS_SERVICE_NAME || 'Vercel Analytics'

export const USERCENTRICS_CHATBASE_SERVICE_NAME =
  process.env.NEXT_PUBLIC_USERCENTRICS_CHATBASE_SERVICE_NAME || 'Chatbase'

export const USERCENTRICS_KLARNA_OSM_SERVICE_NAME =
  process.env.NEXT_PUBLIC_USERCENTRICS_KLARNA_OSM_SERVICE_NAME || 'Klarna On-site Messaging'

export const USERCENTRICS_STATISTICS_SERVICE_NAMES = [
  USERCENTRICS_POSTHOG_SERVICE_NAME,
  USERCENTRICS_GOOGLE_ANALYTICS_SERVICE_NAME,
  USERCENTRICS_CLARITY_SERVICE_NAME,
  USERCENTRICS_VERCEL_ANALYTICS_SERVICE_NAME,
  'Vercel Speed Insights',
  'Sentry Replay'
] as const

export const USERCENTRICS_MARKETING_SERVICE_NAMES = [
  USERCENTRICS_META_SERVICE_NAME,
  USERCENTRICS_MICROSOFT_SERVICE_NAME,
  USERCENTRICS_GOOGLE_ADS_SERVICE_NAME,
  USERCENTRICS_KLARNA_OSM_SERVICE_NAME
] as const

export const USERCENTRICS_PREFERENCES_SERVICE_NAMES = [USERCENTRICS_CHATBASE_SERVICE_NAME] as const

export const USERCENTRICS_REQUIRED_TRACKING_SERVICE_NAMES = [
  USERCENTRICS_GOOGLE_ANALYTICS_SERVICE_NAME,
  USERCENTRICS_GOOGLE_ADS_SERVICE_NAME,
  USERCENTRICS_META_SERVICE_NAME,
  USERCENTRICS_MICROSOFT_SERVICE_NAME,
  USERCENTRICS_CLARITY_SERVICE_NAME,
  USERCENTRICS_POSTHOG_SERVICE_NAME
] as const
