steps:
  - name: gcr.io/cloud-builders/docker
    id: build-css-insight-mcp
    args:
      - build
      - -f
      - Dockerfile.mcp-css
      - -t
      - ${_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    id: push-css-insight-mcp
    args:
      - push
      - ${_IMAGE}

substitutions:
  _IMAGE: europe-west1-docker.pkg.dev/project-c683eb2c-20ae-4ec2-ac3/cloud-run-source-deploy/utekos-css-insight-mcp:latest
