allowBuilds:
  '@google/genai': false
  '@sentry-internal/node-cpu-profiler': true
  '@sentry/cli': true
  '@swc/core': true
  '@vygruppen/spor-react': true
  core-js: false
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

allowedDeprecatedVersions:
  node-domexception: 1.0.0
  tsconfck: 3.1.6

patchedDependencies:
  next@16.2.9: patches/next@16.2.9.patch

peerDependencyRules:
  allowedVersions:
    'tsconfck>typescript': 6.0.3
