// Path: types/tracking/meta/event/MetaEventType.ts

export type MetaEventType =
  | 'PageView'
  | 'ViewContent'
  | 'ViewCategory'
  | 'ViewItemList'
  | 'SelectItem'
  | 'AddToCart'
  | 'ViewCart'
  | 'RemoveFromCart'
  | 'InitiateCheckout'
  | 'Purchase'
  | 'Refund'
  | 'Search'
  | 'CompleteRegistration'
  | 'HeroInteract'
  | 'InteractWithAccordion'
  | 'OpenQuickView'
  | 'Lead'
  | 'LandingCTAClick'
  | 'LandingSectionView'
  | 'LandingScrollDepth'
